name: build
on:
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
      
    - name: Set up node
      uses: actions/setup-node@v1
  
    - uses: olegtarasov/get-tag@v2
  
    - run: npm ci
    - run: npm run build
      
    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "./build/style.min.css,./build/style.user.css"
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
